package com.snapsnake.comfyremote;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.InputType;
import android.text.TextUtils;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.net.URL;
import java.net.URLEncoder;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class ComfyCacheActivity extends Activity {
    private static final String VERSION = "0.12.1-cache-real-templates";
    private static final String PREFS = "comfy_cache_native_v1";
    private static final String OLD_REMOTE = "comfyui_remote_prefs";
    private static final String OLD_TEMPLATES = "comfyui_template_cache";
    private static final int REQ_JSON = 9911;
    private static final MediaType JSON = MediaType.parse("application/json; charset=utf-8");
    private static final ExecutorService IO = Executors.newFixedThreadPool(4);
    private static final OkHttpClient HTTP = new OkHttpClient.Builder().connectTimeout(15, TimeUnit.SECONDS).readTimeout(60, TimeUnit.SECONDS).writeTimeout(60, TimeUnit.SECONDS).retryOnConnectionFailure(true).build();
    private final Handler ui = new Handler(Looper.getMainLooper());
    private LinearLayout root, top, content, nav, list;
    private ScrollView scroll;
    private EditText url, cfId, cfSecret, jsonBox, search;
    private TextView status, meta;
    private String screen = "create", query = "", activeBase = "", promptId = "", lastOutput = "";
    private JSONObject workflow;
    private long templatesAt = 0;
    private boolean loading = false;
    private final ArrayList<Tpl> templates = new ArrayList<>();
    private final ArrayList<Field> fields = new ArrayList<>();

    private static class Tpl {
        String source="default", name="", title="", desc="", cat="Templates", media="webp";
        String id(){return source+"/"+name;}
        JSONObject json() throws Exception {return new JSONObject().put("source",source).put("name",name).put("title",title).put("desc",desc).put("cat",cat).put("media",media);} 
        static Tpl from(JSONObject o){Tpl t=new Tpl(); if(o==null)return t; t.source=o.optString("source","default"); t.name=o.optString("name",""); t.title=o.optString("title",t.name); t.desc=o.optString("desc",o.optString("description","")); t.cat=o.optString("cat",o.optString("category","Templates")); t.media=o.optString("media",o.optString("mediaSubtype","webp")); return t;}
    }
    private static class Field {String node,key; EditText edit; Field(String n,String k,EditText e){node=n;key=k;edit=e;}}

    @Override protected void onCreate(Bundle b){super.onCreate(b); build(); load(); render(); bars();}

    private void build(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setFitsSystemWindows(true); root.setBackgroundColor(bg());
        top=new LinearLayout(this); top.setOrientation(LinearLayout.VERTICAL); top.setPadding(dp(18),dp(12),dp(18),dp(12)); top.setBackgroundColor(surface()); root.addView(top,new LinearLayout.LayoutParams(-1,-2));
        top.addView(title("ComfyUI Mobile",20)); top.addView(muted(VERSION,11)); url=input("https://comfyui.example.com",true); top.addView(url,lp(-1,46,0,8,0,8));
        LinearLayout tr=row(); tr.addView(btn("Test",false,this::test),weight(42)); tr.addView(btn("Hide",false,()->top.setVisibility(View.GONE)),weight(42)); tr.addView(btn("Templates",true,()->{screen="templates";render();}),weight(42)); top.addView(tr,new LinearLayout.LayoutParams(-1,dp(42)));
        top.addView(muted("Cloudflare Access optional",12),lp(-1,-2,0,8,0,4)); cfId=input("CF-Access-Client-Id",true); top.addView(cfId,new LinearLayout.LayoutParams(-1,dp(42))); cfSecret=input("CF-Access-Client-Secret",true); cfSecret.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD); top.addView(cfSecret,lp(-1,42,0,6,0,0));
        scroll=new ScrollView(this); scroll.setBackgroundColor(bg()); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(20),dp(16),dp(20),dp(20)); scroll.addView(content); root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=row(); nav.setGravity(Gravity.CENTER); nav.setPadding(dp(14),dp(8),dp(14),dp(8)); nav.setBackgroundColor(surface()); root.addView(nav,new LinearLayout.LayoutParams(-1,dp(78))); setContentView(root);
    }

    private void load(){
        SharedPreferences p=prefs(), old=getSharedPreferences(OLD_REMOTE, Context.MODE_PRIVATE); String u=first(p.getString("url",""),old.getString("comfyui_url","")); url.setText(u); cfId.setText(first(p.getString("cfId",""),old.getString("cf_access_client_id",""))); cfSecret.setText(first(p.getString("cfSecret",""),old.getString("cf_access_client_secret",""))); if(!u.trim().isEmpty())top.setVisibility(View.GONE); lastOutput=p.getString("lastOutput","");
        try{workflow=new JSONObject(p.getString("workflow","{}")); if(workflow.length()==0)workflow=null;}catch(Exception e){workflow=null;}
        templatesAt=p.getLong("templatesAt",0); readTemplates(p.getString("templates","[]")); if(templates.isEmpty())loadOldTemplates();
    }
    private void loadOldTemplates(){SharedPreferences p=getSharedPreferences(OLD_TEMPLATES,Context.MODE_PRIVATE); String[] keys={"template_cards_stable_v1","template_cards_v4","template_cards_v3","template_cards"}; String[] times={"template_cards_stable_updated_v1","template_cards_updated_at_v4","template_cards_updated_at_v3","template_cards_updated_at"}; for(int i=0;i<keys.length&&templates.isEmpty();i++){readTemplates(p.getString(keys[i],"[]")); templatesAt=p.getLong(times[i],templatesAt);} if(!templates.isEmpty())saveTemplates();}

    private void render(){fields.clear(); content.removeAllViews(); nav.removeAllViews(); nav.addView(navItem("⊞","Create","create"),weight(58)); nav.addView(navItem("⌘","Nodes","nodes"),weight(58)); nav.addView(navItem("▦","Templates","templates"),weight(58)); nav.addView(navItem("▷","Run","run"),weight(58)); nav.addView(navItem("▧","Output","output"),weight(58)); if(screen.equals("templates"))templatesScreen(); else if(screen.equals("nodes"))nodesScreen(); else if(screen.equals("run"))runScreen(); else if(screen.equals("output"))outputScreen(); else createScreen(); scroll.post(()->scroll.scrollTo(0,0));}
    private void createScreen(){content.addView(chip(),sec()); content.addView(header("Create",workflow==null?"Load a cached ComfyUI template or import JSON.":workflow.length()+" nodes loaded."),sec()); LinearLayout c=card(false); c.addView(cardTitle("‹/›","Workflow")); LinearLayout r=row(); r.setPadding(0,dp(10),0,dp(10)); r.addView(btn("▦ Templates",false,()->{screen="templates";render();}),weight(46)); r.addView(btn("⇩ Import JSON",true,this::chooseJson),weight(46)); c.addView(r); if(workflow==null){c.addView(label("Paste workflow JSON")); jsonBox=input("Paste workflow/API JSON here…",false); jsonBox.setSingleLine(false); jsonBox.setGravity(Gravity.TOP|Gravity.LEFT); jsonBox.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE); c.addView(jsonBox,new LinearLayout.LayoutParams(-1,dp(150))); c.addView(btn("Apply JSON",true,()->importJson(jsonBox.getText().toString())),new LinearLayout.LayoutParams(-1,dp(44)));}else{c.addView(muted("Edit fields in Nodes or execute in Run.",13));} content.addView(c,sec());}
    private void templatesScreen(){content.addView(chip(),sec()); content.addView(header("Templates","Cached real templates from your ComfyUI"),sec()); LinearLayout tools=card(false); search=bare("Search cached templates…",true); search.setText(query); tools.addView(search,new LinearLayout.LayoutParams(-1,dp(46))); meta=muted("",12); tools.addView(meta); LinearLayout r=row(); r.setPadding(0,dp(8),0,0); r.addView(btn(loading?"Loading…":"Load/Update Cache",true,this::loadCache),weight(44)); r.addView(btn("Clear Search",false,()->{query="";search.setText("");refreshList();}),weight(44)); tools.addView(r); status=muted("Only real ComfyUI templates are cached. No built-in fake templates.",12); status.setSingleLine(true); status.setEllipsize(TextUtils.TruncateAt.END); tools.addView(status); content.addView(tools,sec()); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); content.addView(list); search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){} public void onTextChanged(CharSequence s,int a,int b,int c){query=String.valueOf(s);refreshList();} public void afterTextChanged(Editable e){}}); refreshList();}
    private void refreshList(){if(list==null)return; list.removeAllViews(); if(meta!=null)meta.setText((templates.isEmpty()?"○":"●")+" Cached "+templates.size()+" · "+(templatesAt>0?timeAgo(templatesAt):"no cache yet")); String q=query.toLowerCase(Locale.US).trim(); int shown=0; for(Tpl t:templates){String hay=(t.title+" "+t.name+" "+t.desc+" "+t.cat).toLowerCase(Locale.US); if(q.isEmpty()||hay.contains(q)){list.addView(tplRow(t),sec()); shown++;}} if(shown==0)list.addView(muted(templates.isEmpty()?"No cached templates. Tap Load/Update Cache once when ComfyUI is reachable.":"Nothing found.",14));}
    private View tplRow(Tpl t){LinearLayout r=card(false); r.setOrientation(LinearLayout.HORIZONTAL); r.setGravity(Gravity.CENTER_VERTICAL); ImageView img=new ImageView(this); img.setImageResource(com.snapsnake.comfyremote.R.drawable.ic_launcher); img.setScaleType(ImageView.ScaleType.CENTER_CROP); r.addView(img,new LinearLayout.LayoutParams(dp(106),dp(82))); LinearLayout b=new LinearLayout(this); b.setOrientation(LinearLayout.VERTICAL); b.setPadding(dp(12),0,0,0); r.addView(b,new LinearLayout.LayoutParams(0,dp(82),1)); b.addView(title(first(t.title,t.name),16)); b.addView(muted(shortText(first(t.desc,t.cat),120),12)); r.addView(muted("›",28),new LinearLayout.LayoutParams(dp(24),dp(82))); r.setOnClickListener(v->openTemplate(t)); loadPreview(img,t); return r;}
    private void nodesScreen(){content.addView(chip(),sec()); content.addView(header("Nodes","Imported workflow nodes."),sec()); list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); content.addView(list); if(workflow==null){list.addView(muted("No workflow imported.",14));return;} LinkedHashMap<String,ArrayList<String>> groups=new LinkedHashMap<>(); for(String id:nodeIds()){JSONObject n=workflow.optJSONObject(id); String g=group(n); ArrayList<String> a=groups.get(g); if(a==null){a=new ArrayList<>();groups.put(g,a);} a.add(id);} for(String g:groups.keySet()){LinearLayout gc=card(true);gc.addView(title(g,16));gc.addView(muted(groups.get(g).size()+" nodes",12));list.addView(gc,sec()); for(String id:groups.get(g))list.addView(nodeRow(id),sec());}}
    private View nodeRow(String id){JSONObject n=workflow.optJSONObject(id);LinearLayout c=card(false);c.addView(title(titleOf(n),16));c.addView(muted("#"+id+" · "+n.optString("class_type","Node"),12));c.setOnClickListener(v->editNode(id));return c;}
    private void editNode(String id){content.removeAllViews(); JSONObject n=workflow.optJSONObject(id); content.addView(header(titleOf(n),"#"+id+" · "+n.optString("class_type","")),sec()); LinearLayout c=card(false); JSONObject in=n.optJSONObject("inputs"); if(in!=null){Iterator<String> it=in.keys(); while(it.hasNext()){String k=it.next(); Object val=in.opt(k); if(val instanceof JSONArray)continue; c.addView(label(k)); EditText e=input("",false); e.setText(String.valueOf(val)); c.addView(e,new LinearLayout.LayoutParams(-1,dp(44))); fields.add(new Field(id,k,e));}} c.addView(btn("Apply",true,()->{applyFields();saveWorkflow();screen="nodes";render();}),new LinearLayout.LayoutParams(-1,dp(44))); content.addView(c,sec());}
    private void runScreen(){content.addView(chip(),sec());content.addView(header("Run","Execute workflow."),sec());LinearLayout c=card(false);c.addView(title(workflow==null?"No workflow loaded":"Workflow loaded",18));c.addView(muted(workflow==null?"Choose template or import JSON first.":workflow.length()+" nodes ready.",13));c.addView(btn("Run",true,this::runWorkflow),new LinearLayout.LayoutParams(-1,dp(44)));content.addView(c,sec());}
    private void outputScreen(){content.addView(chip(),sec());content.addView(header("Output","Recent output."),sec());LinearLayout c=card(false);c.addView(muted(lastOutput.isEmpty()?"No output yet.":lastOutput,13));if(!lastOutput.isEmpty())c.addView(btn("Open",true,()->openUrl(lastOutput)),new LinearLayout.LayoutParams(-1,dp(44)));content.addView(c,sec());}

    private void loadCache(){if(loading)return; saveConn(); loading=true; toast("Loading template cache..."); IO.execute(()->{ArrayList<Tpl> got=new ArrayList<>();String err="";try{JSONArray index=new JSONArray(get("/templates/index.json"));for(int i=0;i<index.length();i++){JSONObject cat=index.optJSONObject(i);if(cat==null)continue;String src=first(cat.optString("moduleName","default"),"default");String catName=first(cat.optString("localizedTitle",cat.optString("title",src)),"Templates");JSONArray arr=cat.optJSONArray("templates");if(arr==null)continue;for(int j=0;j<arr.length();j++){JSONObject o=arr.optJSONObject(j);if(o==null)continue;Tpl t=new Tpl();t.source=src;t.name=o.optString("name","").trim();t.title=o.optString("localizedTitle",o.optString("title",t.name));t.desc=o.optString("localizedDescription",o.optString("description",""));t.cat=catName;t.media=o.optString("mediaSubtype","webp");if(valid(t))got.add(t);}}}catch(Exception e){err=e.getMessage();}String fe=err;ui.post(()->{loading=false;if(!got.isEmpty()){templates.clear();templates.addAll(got);templatesAt=System.currentTimeMillis();saveTemplates();refreshList();toast("Cached "+got.size()+" templates");preload(got);}else toast("Cache update failed"+(templates.isEmpty()?": ":"; kept old cache. ")+(fe==null?"":fe));});});}
    private void preload(ArrayList<Tpl> items){IO.execute(()->{for(Tpl t:items)try{write(rawFile(t),get(path(t)));}catch(Exception ignored){}});}
    private void openTemplate(Tpl t){toast("Opening "+first(t.title,t.name));IO.execute(()->{try{String raw=read(rawFile(t));if(raw.trim().isEmpty())raw=readLegacy(t);if(raw.trim().isEmpty()){raw=get(path(t));write(rawFile(t),raw);}JSONObject r=ComfyWorkflowConverter.importResult(new JSONObject(raw),objectInfo());ui.post(()->handleImport(r));}catch(Exception e){ui.post(()->toast("Template failed: "+e.getMessage()));}});}
    private JSONObject objectInfo(){try{JSONObject o=new JSONObject(get("/api/object_info"));prefs().edit().putString("objectInfo",o.toString()).apply();return o;}catch(Exception e){try{return new JSONObject(prefs().getString("objectInfo","{}"));}catch(Exception x){return new JSONObject();}}}
    private void importJson(String raw){IO.execute(()->{try{JSONObject r=ComfyWorkflowConverter.importResult(new JSONObject(raw),objectInfo());ui.post(()->handleImport(r));}catch(Exception e){ui.post(()->toast("Import failed: "+e.getMessage()));}});}
    private void handleImport(JSONObject r){try{if(!r.optBoolean("ok",false)){toast("Import failed: "+r.optString("error"));return;}workflow=r.optJSONObject("prompt");if(workflow==null)workflow=new JSONObject(r.optString("prompt","{}"));saveWorkflow();screen="create";render();toast("Imported "+workflow.length()+" nodes");}catch(Exception e){toast("Import failed: "+e.getMessage());}}
    private void runWorkflow(){if(workflow==null){toast("Import workflow first");return;}applyFields();saveWorkflow();IO.execute(()->{try{JSONObject p=new JSONObject().put("prompt",workflow).put("client_id","comfyui-mobile-"+System.currentTimeMillis());JSONObject r=new JSONObject(post("/prompt",p.toString()));promptId=r.optString("prompt_id","");ui.post(()->toast("Queued"));}catch(Exception e){ui.post(()->toast("Run failed: "+e.getMessage()));}});}
    private void test(){saveConn();IO.execute(()->{try{get("/system_stats");ui.post(()->toast("Connection OK: "+host(activeBase)));}catch(Exception e){ui.post(()->toast("Connection failed: "+e.getMessage()));}});}

    private String get(String path)throws Exception{return request(path,null);} private String post(String path,String body)throws Exception{return request(path,body);} private String request(String path,String body)throws Exception{Exception last=null;for(String b:bases()){try{Request.Builder rb=new Request.Builder().url(b+path).header("Accept","application/json,*/*").header("User-Agent","ComfyUI-Mobile/"+VERSION);for(Map.Entry<String,String>h:headers().entrySet())rb.header(h.getKey(),h.getValue());if(body!=null)rb.post(RequestBody.create(body,JSON));try(Response r=HTTP.newCall(rb.build()).execute()){String text=r.body()==null?"":r.body().string();if(!r.isSuccessful())throw new Exception("HTTP "+r.code()+": "+shortText(text,120));activeBase=b;prefs().edit().putString("url",b).apply();return text;}}catch(Exception e){last=e;}}throw last==null?new Exception("No valid URL"):last;}
    private ArrayList<String>bases(){ArrayList<String>a=new ArrayList<>();String r=rawUrl();if(r.isEmpty())return a;if(r.startsWith("http://")||r.startsWith("https://")){addBase(a,r);try{URL u=new URL(strip(r));addBase(a,("https".equals(u.getProtocol())?"http":"https")+"://"+u.getHost());}catch(Exception ignored){}}else{addBase(a,"https://"+r);addBase(a,"http://"+r);}return a;} private void addBase(ArrayList<String>a,String s){try{URL u=new URL(strip(s));String b=u.getProtocol()+"://"+u.getHost()+(u.getPort()>0?":"+u.getPort():"");if(!a.contains(b))a.add(b);}catch(Exception ignored){}}
    private Map<String,String>headers(){HashMap<String,String>h=new HashMap<>();String id=cfId.getText().toString().trim(),sec=cfSecret.getText().toString().trim();if(!id.isEmpty()&&!sec.isEmpty()){h.put("CF-Access-Client-Id",id);h.put("CF-Access-Client-Secret",sec);}return h;}
    private String rawUrl(){String s=url.getText().toString().trim();if(s.isEmpty())s=prefs().getString("url","");return strip(s);} private String strip(String s){if(s==null)return"";s=s.trim();while(s.endsWith("/"))s=s.substring(0,s.length()-1);return s;}
    private void loadPreview(ImageView img,Tpl t){IO.execute(()->{try{File f=previewFile(t,"webp");if(!f.exists())write(f,bytes(previewPath(t,"webp")));Bitmap b=BitmapFactory.decodeFile(f.getAbsolutePath());if(b!=null)ui.post(()->img.setImageBitmap(b));}catch(Exception ignored){}});} private byte[] bytes(String path)throws Exception{Request r=new Request.Builder().url(activeBase()+path).build();try(Response resp=HTTP.newCall(r).execute()){return resp.body()==null?new byte[0]:resp.body().bytes();}}
    private void chooseJson(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ_JSON);}@Override protected void onActivityResult(int req,int res,Intent d){super.onActivityResult(req,res,d);if(req==REQ_JSON&&res==RESULT_OK&&d!=null&&d.getData()!=null)try{importJson(readUri(d.getData()));}catch(Exception e){toast(e.getMessage());}}
    private void readTemplates(String s){try{JSONArray a=new JSONArray(s==null?"[]":s);for(int i=0;i<a.length();i++){Tpl t=Tpl.from(a.optJSONObject(i));if(valid(t))templates.add(t);}}catch(Exception ignored){}} private void saveTemplates(){JSONArray a=new JSONArray();for(Tpl t:templates)try{a.put(t.json());}catch(Exception ignored){}prefs().edit().putString("templates",a.toString()).putLong("templatesAt",templatesAt).apply();}
    private boolean valid(Tpl t){return t!=null&&!t.name.trim().isEmpty()&&!t.source.trim().isEmpty();} private String path(Tpl t){return "default".equals(t.source)?"/templates/"+encPath(t.name)+".json":"/api/workflow_templates/"+encPath(t.source)+"/"+encPath(t.name)+".json";} private String previewPath(Tpl t,String ext){return "default".equals(t.source)?"/templates/"+encPath(t.name)+"-1."+ext:"/api/workflow_templates/"+encPath(t.source)+"/"+encPath(t.name)+"."+ext;} private File rawFile(Tpl t){return new File(cacheDir("raw"),sha1(activeBase()+"|"+t.id())+".json");} private File previewFile(Tpl t,String ext){return new File(cacheDir("preview"),sha1(activeBase()+"|"+t.id())+"."+ext);} private String readLegacy(Tpl t){return"";}
    private ArrayList<String>nodeIds(){ArrayList<String>a=new ArrayList<>();if(workflow==null)return a;Iterator<String>it=workflow.keys();while(it.hasNext())a.add(it.next());Collections.sort(a);return a;} private String group(JSONObject n){JSONObject m=n==null?null:n.optJSONObject("_meta");return first(m==null?"":m.optString("group",m.optString("group_name","")),"General");} private String titleOf(JSONObject n){JSONObject m=n==null?null:n.optJSONObject("_meta");return first(m==null?"":m.optString("title",""),n==null?"Node":n.optString("class_type","Node"));} private void applyFields(){for(Field f:fields)try{workflow.getJSONObject(f.node).getJSONObject("inputs").put(f.key,f.edit.getText().toString());}catch(Exception ignored){}} private void saveWorkflow(){prefs().edit().putString("workflow",workflow==null?"{}":workflow.toString()).apply();}
    private SharedPreferences prefs(){return getSharedPreferences(PREFS,Context.MODE_PRIVATE);} private void saveConn(){prefs().edit().putString("url",rawUrl()).putString("cfId",cfId.getText().toString()).putString("cfSecret",cfSecret.getText().toString()).apply();} private File cacheDir(String c){File f=new File(getFilesDir(),"template_cache2/"+c);if(!f.exists())f.mkdirs();return f;} private String read(File f){try{return new String(readBytes(f),"UTF-8");}catch(Exception e){return"";}} private byte[]readBytes(File f){try{ByteArrayOutputStream o=new ByteArrayOutputStream();InputStream in=new FileInputStream(f);byte[]b=new byte[8192];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toByteArray();}catch(Exception e){return new byte[0];}} private void write(File f,String s){try{write(f,s.getBytes("UTF-8"));}catch(Exception ignored){}} private void write(File f,byte[]b){try{File p=f.getParentFile();if(p!=null&&!p.exists())p.mkdirs();FileOutputStream o=new FileOutputStream(f);o.write(b);o.close();}catch(Exception ignored){}}
    private View chip(){LinearLayout c=row();c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(12),0,dp(12),0);c.setBackground(bgDrawable(surface(),12,stroke(),1));c.addView(text(activeBase().isEmpty()?"○":"●",16,activeBase().isEmpty()?mutedColor():Color.rgb(66,184,93)),new LinearLayout.LayoutParams(dp(24),dp(38)));TextView l=muted(activeBase().isEmpty()?"Tap to set URL":host(activeBase()),12);c.addView(l,new LinearLayout.LayoutParams(0,dp(38),1));c.setOnClickListener(v->top.setVisibility(top.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));return c;} private View header(String h,String s){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.addView(title(h,28));b.addView(muted(s,14));return b;} private View cardTitle(String i,String s){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.addView(title(i,16),new LinearLayout.LayoutParams(dp(34),dp(34)));r.addView(title(s,19));return r;} private View navItem(String i,String l,String target){boolean sel=target.equals(screen);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setBackground(sel?bgDrawable(Color.rgb(37,31,22),12,accent(),1):null);b.addView(text(i,18,sel?accent():mutedColor()));b.addView(text(l,10,sel?accent():mutedColor()));b.setOnClickListener(v->{screen=target;render();});return b;}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);return r;} private LinearLayout card(boolean a){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackground(bgDrawable(surface(),16,a?accent():stroke(),1));return c;} private Button btn(String s,boolean p,Runnable r){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(p?accent():Color.WHITE);b.setBackground(bgDrawable(p?Color.rgb(44,35,25):surface2(),12,p?accent():stroke(),1));b.setOnClickListener(v->r.run());return b;} private EditText input(String h,boolean one){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(one);e.setTextColor(Color.WHITE);e.setHintTextColor(mutedColor());e.setBackground(bgDrawable(surface2(),12,stroke(),1));e.setPadding(dp(12),0,dp(12),0);return e;} private EditText bare(String h,boolean one){EditText e=input(h,one);e.setBackgroundColor(Color.TRANSPARENT);return e;}
    private TextView title(String s,int sp){TextView t=text(s,sp,Color.WHITE);t.setTypeface(Typeface.DEFAULT_BOLD);t.setMaxLines(3);t.setEllipsize(TextUtils.TruncateAt.END);return t;} private TextView label(String s){return text(s,13,Color.rgb(210,210,216));} private TextView muted(String s,int sp){return text(s,sp,mutedColor());} private TextView text(String s,int sp,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setIncludeFontPadding(false);t.setPadding(dp(2),0,dp(2),dp(5));return t;} private GradientDrawable bgDrawable(int c,int r,int sc,int sw){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));d.setStroke(dp(sw),sc);return d;} private LinearLayout.LayoutParams sec(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));return p;} private LinearLayout.LayoutParams weight(int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(h),1);p.setMargins(dp(4),0,dp(4),0);return p;} private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h<0?h:dp(h));p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private int bg(){return Color.rgb(18,18,19);} private int surface(){return Color.rgb(28,28,30);} private int surface2(){return Color.rgb(33,33,36);} private int stroke(){return Color.rgb(48,48,52);} private int mutedColor(){return Color.rgb(170,170,178);} private int accent(){return Color.rgb(218,143,60);} private void bars(){Window w=getWindow();w.setStatusBarColor(bg());w.setNavigationBarColor(bg());} private void toast(String s){Toast.makeText(this,shortText(s,220),Toast.LENGTH_LONG).show();if(status!=null)status.setText(shortText(s,220));} private String host(String b){try{return new URL(b).getHost();}catch(Exception e){return b;}} private String first(String a,String b){return a!=null&&!a.trim().isEmpty()?a:b;} private String shortText(String s,int n){return s==null?"":s.length()>n?s.substring(0,n-1)+"…":s;} private String timeAgo(long t){long m=(System.currentTimeMillis()-t)/60000;return m<1?"just now":m+"m ago";} private String encPath(String s){try{return URLEncoder.encode(s,"UTF-8").replace("%2F","/");}catch(Exception e){return s;}} private String sha1(String s){try{MessageDigest md=MessageDigest.getInstance("SHA-1");byte[]d=md.digest(s.getBytes("UTF-8"));StringBuilder sb=new StringBuilder();for(byte b:d)sb.append(String.format(Locale.US,"%02x",b&255));return sb.toString();}catch(Exception e){return String.valueOf(s.hashCode());}} private void openUrl(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){toast("Could not open URL");}}
}
