package com.snapsnake.comfyremote;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.text.Editable;
import android.text.InputType;
import android.text.TextUtils;
import android.text.TextWatcher;
import android.util.LruCache;
import android.view.Gravity;
import android.view.View;
import android.view.Window;
import android.webkit.CookieManager;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class RescueComfyMobileActivity extends Activity {
    private static final String PREFS = "comfyui_mobile_rescue_v1";
    private static final String OLD_REMOTE_PREFS = "comfyui_remote_prefs";
    private static final String OLD_TEMPLATE_PREFS = "comfyui_template_cache";
    private static final String KEY_URL = "url";
    private static final String KEY_CF_ID = "cf_id";
    private static final String KEY_CF_SECRET = "cf_secret";
    private static final String KEY_WORKFLOW = "workflow";
    private static final String KEY_OPTIONS = "options";
    private static final String KEY_OBJECT_INFO = "object_info";
    private static final String KEY_OUTPUT = "last_output";
    private static final String KEY_TEMPLATES = "templates";
    private static final String KEY_TEMPLATES_AT = "templates_at";
    private static final int REQ_JSON = 7001;
    private static final int PAGE = 60;
    private static final int MAX_BYTES = 32 * 1024 * 1024;
    private static final ExecutorService IO = Executors.newFixedThreadPool(5);
    private static final LruCache<String, Bitmap> PREVIEW_MEM = new LruCache<>(64);

    private final Handler ui = new Handler(Looper.getMainLooper());
    private LinearLayout root, topPanel, content, bottomNav, nodeList, templateList;
    private ScrollView scroll;
    private EditText urlInput, cfIdInput, cfSecretInput, jsonEditor, nodeSearch, templateSearch;
    private TextView status, templateInfo, loadedInfo, updatedInfo, runInfo;
    private ProgressBar progress;
    private JSONObject workflow;
    private JSONObject options = new JSONObject();
    private final ArrayList<FieldRef> fields = new ArrayList<>();
    private final ArrayList<TemplateItem> templates = new ArrayList<>();
    private final Set<String> openGroups = new HashSet<>();
    private String screen = "create";
    private String activeBase = "";
    private String nodeQ = "";
    private String templateQ = "";
    private String promptId = "";
    private String lastOutput = "";
    private int shownTemplates = PAGE;
    private long templatesAt = 0L;
    private int polls = 0;
    private boolean refreshing = false;

    private static class FieldRef { String node, key; EditText edit; FieldRef(String n, String k, EditText e){node=n;key=k;edit=e;} }
    private static class OutputFile { String filename, subfolder, type; OutputFile(String f,String s,String t){filename=f;subfolder=s;type=t;} }
    private static class TemplateItem {
        String source="default", name="", title="", description="", category="Templates", mediaSubtype="webp";
        String id(){return safe(source)+"/"+safe(name);} 
        JSONObject toJson() throws Exception { JSONObject o=new JSONObject(); o.put("source",safe(source)); o.put("name",safe(name)); o.put("title",safe(title)); o.put("description",safe(description)); o.put("category",safe(category)); o.put("mediaSubtype",safe(mediaSubtype)); return o; }
        static TemplateItem fromJson(JSONObject o){ TemplateItem t=new TemplateItem(); if(o==null)return t; t.source=o.optString("source","default"); t.name=o.optString("name",""); t.title=o.optString("title",t.name); t.description=o.optString("description",""); t.category=o.optString("category","Templates"); t.mediaSubtype=o.optString("mediaSubtype","webp"); return t; }
        static String safe(String s){return s==null?"":s;}
    }

    @Override protected void onCreate(Bundle b){ super.onCreate(b); System.setProperty("http.keepAlive","false"); try{CookieManager.getInstance().setAcceptCookie(true);}catch(Exception ignored){} buildShell(); loadState(); render(); applyBars(); }

    private void buildShell(){
        root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setFitsSystemWindows(true); root.setBackgroundColor(bgRoot());
        topPanel=new LinearLayout(this); topPanel.setOrientation(LinearLayout.VERTICAL); topPanel.setPadding(dp(18),dp(12),dp(18),dp(12)); topPanel.setBackgroundColor(surface()); root.addView(topPanel,new LinearLayout.LayoutParams(-1,-2));
        topPanel.addView(title("ComfyUI Mobile",18)); urlInput=input("https://comfyui.example.com",true); topPanel.addView(urlInput,lp(-1,46,0,8,0,8));
        LinearLayout quick=row(); quick.addView(button("Test",false,this::testConnection),weight(42)); quick.addView(button("Create",false,()->{screen="create";render();}),weight(42)); quick.addView(button("Templates",true,()->{screen="templates";render();}),weight(42)); topPanel.addView(quick,new LinearLayout.LayoutParams(-1,dp(42)));
        topPanel.addView(muted("Cloudflare Access optional",12),lp(-1,-2,0,8,0,4)); cfIdInput=input("CF-Access-Client-Id",true); topPanel.addView(cfIdInput,new LinearLayout.LayoutParams(-1,dp(42))); cfSecretInput=input("CF-Access-Client-Secret",true); cfSecretInput.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD); topPanel.addView(cfSecretInput,lp(-1,42,0,6,0,0));
        progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal); progress.setMax(100); progress.setVisibility(View.GONE); root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));
        scroll=new ScrollView(this); scroll.setFillViewport(false); scroll.setBackgroundColor(bgRoot()); scroll.setVerticalScrollBarEnabled(false); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(20),dp(16),dp(20),dp(20)); scroll.addView(content,new ScrollView.LayoutParams(-1,-2)); root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        bottomNav=new LinearLayout(this); bottomNav.setOrientation(LinearLayout.HORIZONTAL); bottomNav.setGravity(Gravity.CENTER); bottomNav.setPadding(dp(14),dp(8),dp(14),dp(8)); bottomNav.setBackgroundColor(surface()); root.addView(bottomNav,new LinearLayout.LayoutParams(-1,dp(78))); setContentView(root);
    }

    private void loadState(){
        SharedPreferences p=prefs(), old=getSharedPreferences(OLD_REMOTE_PREFS,Context.MODE_PRIVATE);
        String u=p.getString(KEY_URL,""); if(u.isEmpty()) u=old.getString("comfyui_url",""); urlInput.setText(u);
        String id=p.getString(KEY_CF_ID,""); if(id.isEmpty()) id=old.getString("cf_access_client_id",""); cfIdInput.setText(id);
        String sec=p.getString(KEY_CF_SECRET,""); if(sec.isEmpty()) sec=old.getString("cf_access_client_secret",""); cfSecretInput.setText(sec);
        if(!safe(u).trim().isEmpty()) topPanel.setVisibility(View.GONE); lastOutput=p.getString(KEY_OUTPUT,"");
        try{workflow=new JSONObject(p.getString(KEY_WORKFLOW,"{}")); if(workflow.length()==0) workflow=null;}catch(Exception e){workflow=null;} try{options=new JSONObject(p.getString(KEY_OPTIONS,"{}"));}catch(Exception e){options=new JSONObject();}
        loadTemplateCache();
    }

    private void saveConn(){ prefs().edit().putString(KEY_URL,rawUrl()).putString(KEY_CF_ID,cfIdInput.getText().toString().trim()).putString(KEY_CF_SECRET,cfSecretInput.getText().toString().trim()).apply(); try{CookieManager.getInstance().flush();}catch(Exception ignored){} }

    private void render(){ fields.clear(); content.removeAllViews(); renderNav(); if("nodes".equals(screen)) renderNodes(); else if("templates".equals(screen)) renderTemplates(); else if("run".equals(screen)) renderRun(); else if("output".equals(screen)) renderOutput(); else renderCreate(); scroll.post(()->scroll.scrollTo(0,0)); }

    private void renderCreate(){ content.addView(statusChip(),section()); content.addView(header("Create", workflow==null?"Choose a template or load workflow JSON.":workflow.length()+" nodes loaded."),section()); LinearLayout c=card(false); c.addView(cardTitle("‹/›","Workflow")); LinearLayout a=row(); a.setPadding(0,dp(10),0,dp(10)); a.addView(button("▦ Templates",false,()->{screen="templates";render();}),weight(46)); a.addView(button("⇩ Import JSON",true,this::chooseJson),weight(46)); c.addView(a); if(workflow!=null){ c.addView(muted("Workflow is loaded. Use Nodes to edit fields or Run to execute.",13)); LinearLayout r=row(); r.setPadding(0,dp(12),0,0); r.addView(button("Nodes",false,()->{screen="nodes";render();}),weight(44)); r.addView(button("Run",true,()->{screen="run";render();}),weight(44)); c.addView(r);} else { c.addView(label("Fallback: paste workflow JSON")); jsonEditor=input("Paste ComfyUI workflow/API JSON here…",false); jsonEditor.setSingleLine(false); jsonEditor.setGravity(Gravity.TOP|Gravity.LEFT); jsonEditor.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS); c.addView(jsonEditor,new LinearLayout.LayoutParams(-1,dp(150))); LinearLayout r=row(); r.setPadding(0,dp(12),0,0); r.addView(button("Load JSON",false,this::chooseJson),weight(44)); r.addView(button("Apply JSON",true,()->importJson(jsonEditor.getText().toString())),weight(44)); c.addView(r);} content.addView(c,section()); LinearLayout tip=card(true); tip.addView(label("Tip")); tip.addView(muted("No WebView overlay. Templates and JSON use the same workflow/subgraph importer.",13)); content.addView(tip,section()); }

    private void renderTemplates(){ content.addView(statusChip(),section()); content.addView(header("Templates","Browse and load workflow templates"),section()); LinearLayout tools=card(false); LinearLayout s=row(); s.setGravity(Gravity.CENTER_VERTICAL); s.setPadding(dp(12),0,dp(10),0); s.setBackground(bg(surface2(),10,stroke(),1)); s.addView(muted("⌕",22),new LinearLayout.LayoutParams(dp(30),-1)); templateSearch=new EditText(this); templateSearch.setSingleLine(true); templateSearch.setText(templateQ); templateSearch.setHint("Search templates…"); templateSearch.setTextColor(Color.WHITE); templateSearch.setHintTextColor(mutedColor()); templateSearch.setTextSize(14); templateSearch.setBackgroundColor(Color.TRANSPARENT); s.addView(templateSearch,new LinearLayout.LayoutParams(0,-1,1)); TextView tune=muted("☷",18); tune.setGravity(Gravity.CENTER); s.addView(tune,new LinearLayout.LayoutParams(dp(32),-1)); tools.addView(s,new LinearLayout.LayoutParams(-1,dp(46))); LinearLayout m=row(); m.setPadding(0,dp(8),0,0); loadedInfo=muted("",12); updatedInfo=muted("",12); updatedInfo.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL); m.addView(loadedInfo,new LinearLayout.LayoutParams(0,dp(30),1)); m.addView(updatedInfo,new LinearLayout.LayoutParams(0,dp(30),1)); tools.addView(m); LinearLayout acts=row(); acts.setPadding(0,dp(4),0,dp(4)); acts.addView(button(refreshing?"⟳ Refreshing…":"⟳ Refresh",true,this::refreshTemplates),weight(42)); acts.addView(button("⌫ Clear",false,()->{templateQ=""; shownTemplates=PAGE; if(templateSearch!=null)templateSearch.setText(""); refreshTemplateList();}),weight(42)); tools.addView(acts); templateInfo=muted("Keeps old cache; network uses retries and connection-close.",12); templateInfo.setSingleLine(true); templateInfo.setEllipsize(TextUtils.TruncateAt.END); tools.addView(templateInfo); content.addView(tools,section()); templateList=new LinearLayout(this); templateList.setOrientation(LinearLayout.VERTICAL); content.addView(templateList,new LinearLayout.LayoutParams(-1,-2)); templateSearch.addTextChangedListener(new TextWatcher(){ public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){templateQ=String.valueOf(s==null?"":s); shownTemplates=PAGE; refreshTemplateList();} public void afterTextChanged(Editable e){} }); refreshTemplateMeta(); refreshTemplateList(); if(templates.isEmpty()&&!rawUrl().isEmpty()) refreshTemplates(); }

    private void refreshTemplates(){ if(refreshing)return; saveConn(); if(baseCandidates().isEmpty()){setStatus("Set a valid ComfyUI URL first."); topPanel.setVisibility(View.VISIBLE); return;} refreshing=true; setStatus("Refreshing templates..."); IO.execute(()->{ ArrayList<TemplateItem> loaded=new ArrayList<>(); String err=""; try{ JSONArray index=new JSONArray(getTextAuto("/templates/index.json")); for(int i=0;i<index.length();i++){ JSONObject cat=index.optJSONObject(i); if(cat==null)continue; String source=nonEmpty(cat.optString("moduleName","default"),"default"); String catTitle=nonEmpty(cat.optString("localizedTitle",cat.optString("title",source)),"Templates"); JSONArray arr=cat.optJSONArray("templates"); if(arr==null)continue; for(int j=0;j<arr.length();j++){ JSONObject raw=arr.optJSONObject(j); if(raw==null)continue; TemplateItem t=new TemplateItem(); t.source=source; t.name=raw.optString("name","").trim(); t.title=raw.optString("localizedTitle",raw.optString("title",t.name)); t.description=raw.optString("localizedDescription",raw.optString("description","")); t.category=catTitle; t.mediaSubtype=raw.optString("mediaSubtype","webp"); if(validTemplate(t)) loaded.add(t);} }}catch(Exception e){err=shortErr(e);} try{ JSONObject custom=new JSONObject(getTextAuto("/api/workflow_templates")); Iterator<String> it=custom.keys(); while(it.hasNext()){ String module=it.next(); JSONArray arr=custom.optJSONArray(module); if(arr==null)continue; for(int i=0;i<arr.length();i++){String n=arr.optString(i,"").trim(); if(n.isEmpty())continue; TemplateItem t=new TemplateItem(); t.source=module; t.name=n; t.title=n; t.description=module; t.category="Custom templates"; loaded.add(t);}}}catch(Exception ignored){} String finalErr=err; ui.post(()->{refreshing=false; if(!loaded.isEmpty()){templates.clear();templates.addAll(loaded);templatesAt=System.currentTimeMillis();saveTemplateCache();refreshTemplateMeta();refreshTemplateList();setStatus("Loaded "+loaded.size()+" templates.");preloadTemplates(new ArrayList<>(loaded));}else{refreshTemplateList(); String msg="Refresh failed: "+(finalErr.isEmpty()?"no templates returned":finalErr); if(!templates.isEmpty()) msg+=". Kept local cache."; setStatus(msg); if(templateInfo!=null)templateInfo.setText(msg);}}); }); }

    private void preloadTemplates(ArrayList<TemplateItem> list){ IO.execute(()->{int ok=0; for(int i=0;i<list.size();i++){ try{TemplateItem t=list.get(i); writeText(rawTemplateFile(t),getTextAuto(templatePath(t))); ok++;}catch(Exception ignored){} if(i%25==0){int done=i+1,count=ok; ui.post(()->setStatus("Caching workflows: "+done+"/"+list.size()+" ready "+count));}} int count=ok; ui.post(()->setStatus("Templates ready. Cached workflows: "+count+"."));}); }

    private void refreshTemplateMeta(){ if(loadedInfo!=null){loadedInfo.setText((templates.isEmpty()?"○":"●")+" Loaded "+templates.size()+" templates");loadedInfo.setTextColor(templates.isEmpty()?mutedColor():accent());} if(updatedInfo!=null)updatedInfo.setText(templatesAt>0?"Updated "+timeAgo(templatesAt):"Not refreshed yet"); }
    private void refreshTemplateList(){ if(templateList==null)return; templateList.removeAllViews(); String q=safe(templateQ).trim().toLowerCase(Locale.US); ArrayList<TemplateItem> m=new ArrayList<>(); for(TemplateItem t:templates) if(validTemplate(t)&&(q.isEmpty()||templateHay(t).toLowerCase(Locale.US).contains(q))) m.add(t); int max=Math.min(shownTemplates,m.size()); for(int i=0;i<max;i++) templateList.addView(templateCard(m.get(i)),section()); if(m.isEmpty()) templateList.addView(muted(templates.isEmpty()?"No templates cached yet. Tap Refresh.":"Nothing found.",14)); if(m.size()>max){LinearLayout more=card(false); more.setGravity(Gravity.CENTER_HORIZONTAL); more.addView(muted("Showing "+max+" of "+m.size()+" templates.",13)); more.addView(button("Show more",false,()->{shownTemplates+=PAGE;refreshTemplateList();}),new LinearLayout.LayoutParams(-1,dp(40))); templateList.addView(more,section());} }
    private View templateCard(TemplateItem t){ LinearLayout r=card(false); r.setOrientation(LinearLayout.HORIZONTAL); r.setGravity(Gravity.CENTER_VERTICAL); r.setPadding(dp(12),dp(12),dp(10),dp(12)); r.setClickable(true); r.setOnClickListener(v->openTemplate(t)); ImageView img=new ImageView(this); img.setScaleType(ImageView.ScaleType.CENTER_CROP); img.setImageResource(R.drawable.ic_launcher); img.setBackground(bg(surface2(),8,stroke(),1)); img.setTag(t.id()); LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(106),dp(82)); ip.setMargins(0,0,dp(12),0); r.addView(img,ip); LinearLayout b=new LinearLayout(this); b.setOrientation(LinearLayout.VERTICAL); b.setGravity(Gravity.CENTER_VERTICAL); r.addView(b,new LinearLayout.LayoutParams(0,dp(82),1)); TextView name=title(displayTitle(t),16); name.setMaxLines(2); name.setEllipsize(TextUtils.TruncateAt.END); b.addView(name); TextView desc=muted(shortText(nonEmpty(t.description,t.category).replace('_',' '),130),12); desc.setMaxLines(2); desc.setEllipsize(TextUtils.TruncateAt.END); b.addView(desc); TextView ar=muted("›",28); ar.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL); r.addView(ar,new LinearLayout.LayoutParams(dp(22),dp(82))); loadPreview(img,t); return r; }

    private void openTemplate(TemplateItem t){ if(!validTemplate(t)){setStatus("Invalid template.");return;} setStatus("Opening template: "+displayTitle(t)); IO.execute(()->{try{ String raw=readText(rawTemplateFile(t)); if(raw.trim().isEmpty()) raw=readLegacyRaw(t); if(raw.trim().isEmpty()){raw=getTextAuto(templatePath(t)); writeText(rawTemplateFile(t),raw);} JSONObject res=ComfyWorkflowConverter.importResult(new JSONObject(raw),objectInfo()); ui.post(()->handleImportResult(res)); }catch(Exception e){ui.post(()->setStatus("Template open failed: "+shortErr(e)));}}); }

    private void renderNodes(){ content.addView(statusChip(),section()); content.addView(header("Nodes","Search, edit and expand grouped nodes."),section()); LinearLayout tools=card(false); LinearLayout s=row(); s.setGravity(Gravity.CENTER_VERTICAL); s.setPadding(dp(12),0,dp(10),0); s.setBackground(bg(surface2(),10,stroke(),1)); s.addView(muted("⌕",22),new LinearLayout.LayoutParams(dp(30),-1)); nodeSearch=new EditText(this); nodeSearch.setSingleLine(true); nodeSearch.setText(nodeQ); nodeSearch.setHint("Search nodes, classes, fields…"); nodeSearch.setTextColor(Color.WHITE); nodeSearch.setHintTextColor(mutedColor()); nodeSearch.setTextSize(14); nodeSearch.setBackgroundColor(Color.TRANSPARENT); s.addView(nodeSearch,new LinearLayout.LayoutParams(0,-1,1)); tools.addView(s,new LinearLayout.LayoutParams(-1,dp(46))); LinearLayout a=row(); a.setPadding(0,dp(10),0,0); a.addView(button("Expand groups",false,this::expandAll),weight(42)); a.addView(button("Clear",false,()->{nodeQ=""; if(nodeSearch!=null)nodeSearch.setText(""); refreshNodes();}),weight(42)); tools.addView(a); content.addView(tools,section()); nodeList=new LinearLayout(this); nodeList.setOrientation(LinearLayout.VERTICAL); content.addView(nodeList,new LinearLayout.LayoutParams(-1,-2)); nodeSearch.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){} public void onTextChanged(CharSequence s,int st,int b,int c){nodeQ=String.valueOf(s==null?"":s);refreshNodes();} public void afterTextChanged(Editable e){}}); refreshNodes(); }
    private void refreshNodes(){ if(nodeList==null)return; nodeList.removeAllViews(); if(workflow==null||workflow.length()==0){nodeList.addView(muted("No workflow imported.",14));return;} String q=safe(nodeQ).trim().toLowerCase(Locale.US); LinkedHashMap<String,ArrayList<String>> groups=new LinkedHashMap<>(); for(String id:nodeIds()){JSONObject n=workflow.optJSONObject(id); if(n==null)continue; String hay=id+" "+nodeTitle(n)+" "+n.optString("class_type")+" "+inputKeysText(n.optJSONObject("inputs"))+" "+groupOf(n); if(!q.isEmpty()&&!hay.toLowerCase(Locale.US).contains(q))continue; String g=groupOf(n); ArrayList<String> list=groups.get(g); if(list==null){list=new ArrayList<>();groups.put(g,list);} list.add(id);} if(groups.isEmpty()){nodeList.addView(muted("Nothing found.",14));return;} boolean grouped=groups.size()>1||!groups.containsKey("General"); for(Map.Entry<String,ArrayList<String>> e:groups.entrySet()){ if(grouped) nodeList.addView(groupCard(e.getKey(),e.getValue()),section()); if(!grouped||openGroups.contains(e.getKey())||!q.isEmpty()) for(String id:e.getValue()) nodeList.addView(nodeCard(id),section()); } }
    private View groupCard(String g,ArrayList<String> ids){ LinearLayout c=card(true); c.setOrientation(LinearLayout.HORIZONTAL); c.setGravity(Gravity.CENTER_VERTICAL); boolean open=openGroups.contains(g); LinearLayout body=new LinearLayout(this); body.setOrientation(LinearLayout.VERTICAL); c.addView(body,new LinearLayout.LayoutParams(0,-2,1)); body.addView(title(g,16)); body.addView(muted(ids.size()+" nodes"+(open?" · expanded":" · tap to expand"),12)); TextView ar=title(open?"⌃":"⌄",22); ar.setGravity(Gravity.CENTER); c.addView(ar,new LinearLayout.LayoutParams(dp(34),dp(42))); c.setOnClickListener(v->{if(openGroups.contains(g))openGroups.remove(g);else openGroups.add(g);refreshNodes();}); return c; }
    private View nodeCard(String id){ JSONObject n=workflow.optJSONObject(id); LinearLayout c=card(false); if(n==null)return c; LinearLayout h=row(); h.setGravity(Gravity.CENTER_VERTICAL); h.addView(title(nodeTitle(n),16),new LinearLayout.LayoutParams(0,-2,1)); TextView ar=muted("›",28); ar.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL); h.addView(ar,new LinearLayout.LayoutParams(dp(28),dp(42))); c.addView(h); c.addView(muted("#"+id+" · "+prettify(n.optString("class_type","Node"))+("General".equals(groupOf(n))?"":" · "+groupOf(n)),12)); JSONObject in=n.optJSONObject("inputs"); LinearLayout chips=row(); chips.setPadding(0,dp(8),0,0); chips.addView(chip(primitiveCount(in)+" fields"),weight(32)); chips.addView(chip(linkCount(in)+" linked"),weight(32)); c.addView(chips); c.setOnClickListener(v->nodeEditor(id)); return c; }
    private void nodeEditor(String id){ fields.clear(); content.removeAllViews(); renderNav(); JSONObject n=workflow.optJSONObject(id); content.addView(statusChip(),section()); content.addView(header(n==null?"Node":nodeTitle(n),n==null?"":"#"+id+" · "+n.optString("class_type","")),section()); LinearLayout c=card(false); if(n==null){c.addView(muted("Node not found.",14));content.addView(c,section());return;} JSONObject in=n.optJSONObject("inputs"); boolean any=false; for(String k:inputKeys(in)){Object v=in.opt(k); if(!primitive(v))continue; any=true; c.addView(label(prettify(k))); EditText e=input("",false); e.setText(v==JSONObject.NULL?"":String.valueOf(v)); boolean multi=k.toLowerCase(Locale.US).contains("prompt")||k.toLowerCase(Locale.US).contains("text")||String.valueOf(v).length()>80; e.setSingleLine(!multi); e.setGravity(multi?Gravity.TOP|Gravity.LEFT:Gravity.CENTER_VERTICAL|Gravity.LEFT); e.setInputType(multi?(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS):(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS)); c.addView(e,new LinearLayout.LayoutParams(-1,multi?dp(110):dp(44))); fields.add(new FieldRef(id,k,e));} if(!any)c.addView(muted("No direct editable fields.",13)); LinearLayout a=row(); a.setPadding(0,dp(12),0,0); a.addView(button("Back",false,()->{screen="nodes";render();}),weight(44)); a.addView(button("Apply",true,()->{applyFields();saveWorkflow();setStatus("Applied.");}),weight(44)); c.addView(a); content.addView(c,section()); }

    private void renderRun(){ content.addView(statusChip(),section()); content.addView(header("Run","Execute workflow."),section()); LinearLayout c=card(false); c.addView(cardTitle("▷",workflow==null?"No workflow loaded":"Workflow loaded")); c.addView(muted(workflow==null?"Choose template or load JSON first.":workflow.length()+" nodes ready.",13)); runInfo=muted("Ready.",13); c.addView(runInfo); LinearLayout a=row(); a.setPadding(0,dp(12),0,0); a.addView(button("Output",false,()->{screen="output";render();}),weight(44)); a.addView(button("Run ▷",true,this::runWorkflow),weight(44)); c.addView(a); content.addView(c,section()); }
    private void renderOutput(){ content.addView(statusChip(),section()); content.addView(header("Output","Recent output."),section()); LinearLayout c=card(false); c.addView(cardTitle("▧","Recent Output")); if(safe(lastOutput).isEmpty()) c.addView(muted("No output yet.",14)); else { c.addView(muted(shortText(lastOutput,300),12)); c.addView(button("Open output",true,()->openUrl(lastOutput)),new LinearLayout.LayoutParams(-1,dp(44))); } content.addView(c,section()); }

    private void chooseJson(){ Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT); i.addCategory(Intent.CATEGORY_OPENABLE); i.setType("*/*"); i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION); try{startActivityForResult(Intent.createChooser(i,"Choose ComfyUI workflow JSON"),REQ_JSON);}catch(Exception e){setStatus("No file picker available.");} }
    @Override protected void onActivityResult(int req,int res,Intent data){ super.onActivityResult(req,res,data); if(req==REQ_JSON&&res==RESULT_OK&&data!=null&&data.getData()!=null){try{importJson(readUri(data.getData()));}catch(Exception e){setStatus("Could not read JSON: "+shortErr(e));}} }
    private void importJson(String raw){ if(safe(raw).trim().isEmpty()){setStatus("Empty JSON.");return;} setStatus("Importing workflow..."); IO.execute(()->{try{JSONObject r=ComfyWorkflowConverter.importResult(new JSONObject(raw),objectInfo()); ui.post(()->handleImportResult(r));}catch(Exception e){ui.post(()->setStatus("Workflow import failed: "+shortErr(e)));}}); }
    private void handleImportResult(JSONObject r){ try{ if(!r.optBoolean("ok",false)){setStatus("Import failed: "+r.optString("error"));return;} workflow=r.optJSONObject("prompt"); if(workflow==null) workflow=new JSONObject(r.optString("prompt","{}")); options=r.optJSONObject("options"); if(options==null)options=new JSONObject(); saveWorkflow(); screen="create"; setStatus("Imported "+workflow.length()+" nodes."); render(); }catch(Exception e){setStatus("Import failed: "+shortErr(e));} }

    private void runWorkflow(){ if(workflow==null||workflow.length()==0){setStatus("Import a workflow first.");return;} saveConn(); applyFields(); saveWorkflow(); setStatus("Sending prompt..."); IO.execute(()->{try{JSONObject payload=new JSONObject(); payload.put("prompt",workflow); payload.put("client_id","comfyui-mobile-"+System.currentTimeMillis()); JSONObject res=new JSONObject(postJsonAuto("/prompt",payload.toString())); promptId=res.optString("prompt_id",""); if(promptId.isEmpty())throw new Exception("ComfyUI did not return prompt_id"); polls=0; ui.post(()->{setStatus("Queued. Waiting for output...");pollHistory();});}catch(Exception e){ui.post(()->setStatus("Run failed: "+shortErr(e)));}}); }
    private void pollHistory(){ if(promptId.isEmpty())return; polls++; IO.execute(()->{try{OutputFile f=findOutput(new JSONObject(getTextAuto("/history/"+enc(promptId)))); if(f!=null){lastOutput=activeBase()+"/view?filename="+enc(f.filename)+"&type="+enc(f.type)+"&subfolder="+enc(f.subfolder); prefs().edit().putString(KEY_OUTPUT,lastOutput).apply(); ui.post(()->{setStatus("Output ready.");screen="output";render();});return;}}catch(Exception ignored){} if(polls<240)ui.postDelayed(this::pollHistory,2000); else ui.post(()->setStatus("Timed out waiting for output."));}); }
    private OutputFile findOutput(JSONObject h){ try{Iterator<String> p=h.keys(); OutputFile found=null; while(p.hasNext()){JSONObject item=h.optJSONObject(p.next()); JSONObject outs=item==null?null:item.optJSONObject("outputs"); if(outs==null)continue; Iterator<String> nodes=outs.keys(); while(nodes.hasNext()){JSONObject o=outs.optJSONObject(nodes.next()); OutputFile f=firstOutput(o==null?null:o.optJSONArray("videos")); if(f!=null)found=f; f=firstOutput(o==null?null:o.optJSONArray("gifs")); if(f!=null)found=f; f=firstOutput(o==null?null:o.optJSONArray("images")); if(f!=null)found=f;}} return found;}catch(Exception e){return null;} }
    private OutputFile firstOutput(JSONArray a){ if(a==null||a.length()==0)return null; JSONObject f=a.optJSONObject(0); if(f==null)return null; String n=f.optString("filename",""); if(n.isEmpty())return null; return new OutputFile(n,f.optString("subfolder",""),f.optString("type","output")); }

    private void testConnection(){ saveConn(); setStatus("Testing connection..."); IO.execute(()->{try{getTextAuto("/system_stats"); ui.post(()->setStatus("Connection OK: "+hostLabel(activeBase())));}catch(Exception e){ui.post(()->setStatus("Connection failed: "+shortErr(e)));}}); }
    private JSONObject objectInfo(){ try{JSONObject o=new JSONObject(getTextAuto("/api/object_info")); prefs().edit().putString(KEY_OBJECT_INFO,o.toString()).apply(); return o;}catch(Exception e){try{return new JSONObject(prefs().getString(KEY_OBJECT_INFO,"{}"));}catch(Exception x){return new JSONObject();}} }

    private String getTextAuto(String path)throws Exception{Exception last=null; for(String b:baseCandidates()) for(int i=0;i<2;i++) try{String r=getTextUrl(b+path); activeBase=b; prefs().edit().putString(KEY_URL,b).apply(); return r;}catch(Exception e){last=e;} throw last==null?new Exception("No valid URL"):last;}
    private String postJsonAuto(String path,String body)throws Exception{Exception last=null; for(String b:baseCandidates()) for(int i=0;i<2;i++) try{String r=postJsonUrl(b+path,body); activeBase=b; prefs().edit().putString(KEY_URL,b).apply(); return r;}catch(Exception e){last=e;} throw last==null?new Exception("No valid URL"):last;}
    private List<String> baseCandidates(){String raw=rawUrl(); ArrayList<String> out=new ArrayList<>(); if(raw.isEmpty())return out; if(raw.startsWith("//"))raw=raw.substring(2); if(raw.startsWith("http://")||raw.startsWith("https://")){addBase(out,raw); try{URL u=new URL(strip(raw)); addBase(out,("https".equals(u.getProtocol())?"http":"https")+"://"+u.getHost()+(u.getPort()>0?":"+u.getPort():""));}catch(Exception ignored){}} else {addBase(out,"https://"+raw); addBase(out,"http://"+raw);} return out;}
    private void addBase(ArrayList<String> out,String s){String b=strip(s); try{URL u=new URL(b); if(u.getHost()!=null&&!u.getHost().trim().isEmpty()&&!out.contains(b))out.add(b);}catch(Exception ignored){}}
    private String activeBase(){ if(!safe(activeBase).isEmpty())return activeBase; List<String>b=baseCandidates(); return b.isEmpty()?"":b.get(0); }
    private String rawUrl(){String s=urlInput==null?"":urlInput.getText().toString().trim(); if(s.isEmpty())s=prefs().getString(KEY_URL,""); if(s.isEmpty())s=getSharedPreferences(OLD_REMOTE_PREFS,Context.MODE_PRIVATE).getString("comfyui_url",""); return strip(s);}
    private String strip(String s){if(s==null)return"";s=s.trim();while(s.endsWith("/"))s=s.substring(0,s.length()-1);return s;}
    private String getTextUrl(String url)throws Exception{return new String(bytes(url,MAX_BYTES,null),"UTF-8");}
    private String postJsonUrl(String url,String body)throws Exception{return new String(bytes(url,MAX_BYTES,body),"UTF-8");}
    private byte[] bytes(String url,int max,String post)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection(); try{c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setUseCaches(false);c.setRequestProperty("Connection","close");c.setRequestProperty("Accept-Encoding","identity");c.setRequestProperty("Cache-Control","no-cache");c.setRequestProperty("Pragma","no-cache");c.setRequestProperty("User-Agent","Mozilla/5.0 (Android) ComfyUI-Mobile");c.setRequestProperty("Accept","application/json,text/plain,*/*"); for(Map.Entry<String,String> e:authHeaders(url).entrySet()) c.setRequestProperty(e.getKey(),e.getValue()); if(post!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");OutputStream os=c.getOutputStream();os.write(post.getBytes("UTF-8"));os.close();} int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n,total=0;while(in!=null&&(n=in.read(buf))>0){total+=n;if(total>max)throw new Exception("response too large");out.write(buf,0,n);} if(in!=null)in.close(); if(code<200||code>=300)throw new Exception("HTTP "+code+": "+out.toString("UTF-8")); return out.toByteArray();}finally{c.disconnect();}}
    private Map<String,String> authHeaders(String url){HashMap<String,String> h=new HashMap<>();String id=cfIdInput==null?"":cfIdInput.getText().toString().trim();String sec=cfSecretInput==null?"":cfSecretInput.getText().toString().trim(); if(!id.isEmpty()&&!sec.isEmpty()){h.put("CF-Access-Client-Id",id);h.put("CF-Access-Client-Secret",sec);} try{String cookies=CookieManager.getInstance().getCookie(url); if(cookies!=null&&!cookies.trim().isEmpty())h.put("Cookie",cookies);}catch(Exception ignored){} return h;}

    private void loadPreview(ImageView img,TemplateItem t){String mem=activeBase()+"|"+t.id();Bitmap b=PREVIEW_MEM.get(mem); if(b!=null){img.setImageBitmap(b);return;} IO.execute(()->{try{for(String e:previewExts(t)){File f=previewFile(t,e); if(f.exists()&&f.length()>0){showPreview(img,t.id(),mem,f);return;} f=legacyPreviewFile(t,e); if(f.exists()&&f.length()>0){showPreview(img,t.id(),mem,f);return;}} for(String e:previewExts(t)){try{File f=previewFile(t,e); downloadToFile(previewPath(t,e,false),f); showPreview(img,t.id(),mem,f); return;}catch(Exception ignored){} try{File f=previewFile(t,e); downloadToFile(previewPath(t,e,true),f); showPreview(img,t.id(),mem,f); return;}catch(Exception ignored){}}}catch(Exception ignored){}});}
    private void downloadToFile(String path,File f)throws Exception{byte[] data=bytesAuto(path);File p=f.getParentFile(); if(p!=null&&!p.exists())p.mkdirs();FileOutputStream o=new FileOutputStream(f);o.write(data);o.close();}
    private byte[] bytesAuto(String path)throws Exception{Exception last=null;for(String b:baseCandidates())for(int i=0;i<2;i++)try{byte[] r=bytes(b+path,MAX_BYTES,null);activeBase=b;return r;}catch(Exception e){last=e;}throw last==null?new Exception("No valid URL"):last;}
    private void showPreview(ImageView img,String tag,String mem,File f){Bitmap b=decode(f); if(b==null)return; PREVIEW_MEM.put(mem,b); ui.post(()->{Object cur=img.getTag(); if(cur!=null&&String.valueOf(cur).equals(tag))img.setImageBitmap(b);});}
    private Bitmap decode(File f){try{BitmapFactory.Options bd=new BitmapFactory.Options();bd.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),bd);if(bd.outWidth<=0||bd.outHeight<=0)return null;BitmapFactory.Options o=new BitmapFactory.Options();o.inPreferredConfig=Bitmap.Config.RGB_565;o.inSampleSize=1;while((bd.outWidth/o.inSampleSize)>260||(bd.outHeight/o.inSampleSize)>220)o.inSampleSize*=2;return BitmapFactory.decodeFile(f.getAbsolutePath(),o);}catch(Exception e){return null;}}

    private void loadTemplateCache(){templatesAt=prefs().getLong(KEY_TEMPLATES_AT,0);templates.clear();readTemplateArray(prefs().getString(KEY_TEMPLATES,"[]")); if(templates.isEmpty()){SharedPreferences p=getSharedPreferences(OLD_TEMPLATE_PREFS,Context.MODE_PRIVATE); String[] keys={"template_cards_stable_v1","template_cards_v4","template_cards_v3","template_cards"}; String[] times={"template_cards_stable_updated_v1","template_cards_updated_at_v4","template_cards_updated_at_v3","template_cards_updated_at"}; for(int i=0;i<keys.length&&templates.isEmpty();i++){readTemplateArray(p.getString(keys[i],"[]"));templatesAt=p.getLong(times[i],templatesAt);} if(!templates.isEmpty())saveTemplateCache();}}
    private void readTemplateArray(String s){try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){TemplateItem t=TemplateItem.fromJson(a.optJSONObject(i));if(validTemplate(t))templates.add(t);}}catch(Exception ignored){}}
    private void saveTemplateCache(){JSONArray a=new JSONArray();for(TemplateItem t:templates)try{a.put(t.toJson());}catch(Exception ignored){} prefs().edit().putString(KEY_TEMPLATES,a.toString()).putLong(KEY_TEMPLATES_AT,templatesAt).apply();}
    private File rawTemplateFile(TemplateItem t){return new File(cacheDir("raw"),sha1(activeBase()+"|"+t.id())+".json");}
    private String readLegacyRaw(TemplateItem t){for(String base:baseCandidates()){File f=new File(new File(getFilesDir(),"template_cache/raw"),sha1(base+"|"+t.id())+".json");String s=readText(f);if(!s.trim().isEmpty())return s;}return"";}
    private File previewFile(TemplateItem t,String ext){return new File(cacheDir("preview"),sha1(activeBase()+"|"+t.id()+"|"+ext)+"."+ext.replaceAll("[^A-Za-z0-9]",""));}
    private File legacyPreviewFile(TemplateItem t,String ext){String base=activeBase();return new File(new File(getFilesDir(),"template_cache/preview"),sha1(base+"|"+t.id()+"|"+ext)+"."+ext.replaceAll("[^A-Za-z0-9]",""));}
    private File cacheDir(String child){File d=new File(getFilesDir(),"rescue_cache/"+child);if(!d.exists())d.mkdirs();return d;}
    private String templatePath(TemplateItem t){return "default".equals(t.source)?"/templates/"+encPath(t.name)+".json":"/api/workflow_templates/"+encPath(t.source)+"/"+encPath(t.name)+".json";}
    private String previewPath(TemplateItem t,String ext,boolean fallback){return "default".equals(t.source)?"/templates/"+encPath(t.name)+(fallback?"":"-1")+"."+ext:"/api/workflow_templates/"+encPath(t.source)+"/"+encPath(t.name)+"."+ext;}
    private ArrayList<String> previewExts(TemplateItem t){LinkedHashSet<String> e=new LinkedHashSet<>();String s=safe(t.mediaSubtype).trim().toLowerCase(Locale.US);if(!s.isEmpty())e.add(s);Collections.addAll(e,"webp","png","jpg","jpeg","gif");return new ArrayList<>(e);}

    private List<String> nodeIds(){ArrayList<String> ids=new ArrayList<>();if(workflow==null)return ids;Iterator<String> it=workflow.keys();while(it.hasNext())ids.add(it.next());Collections.sort(ids,(a,b)->a.compareTo(b));return ids;}
    private String nodeTitle(JSONObject n){JSONObject m=n==null?null:n.optJSONObject("_meta");return prettify(nonEmpty(m==null?"":m.optString("title",""),n==null?"Node":n.optString("class_type","Node")));}
    private String groupOf(JSONObject n){JSONObject m=n==null?null:n.optJSONObject("_meta");return nonEmpty(prettify(m==null?"":m.optString("group",m.optString("group_name",""))),"General");}
    private List<String> inputKeys(JSONObject o){ArrayList<String> k=new ArrayList<>();if(o==null)return k;Iterator<String> it=o.keys();while(it.hasNext())k.add(it.next());Collections.sort(k);return k;}
    private String inputKeysText(JSONObject o){StringBuilder sb=new StringBuilder();for(String k:inputKeys(o))sb.append(' ').append(k);return sb.toString();}
    private boolean primitive(Object v){return v==JSONObject.NULL||v instanceof String||v instanceof Number||v instanceof Boolean;}
    private int primitiveCount(JSONObject o){int n=0;for(String k:inputKeys(o))if(primitive(o.opt(k)))n++;return n;}
    private int linkCount(JSONObject o){int n=0;for(String k:inputKeys(o))if(o.optJSONArray(k)!=null)n++;return n;}
    private void expandAll(){if(workflow!=null)for(String id:nodeIds())openGroups.add(groupOf(workflow.optJSONObject(id)));refreshNodes();}
    private void applyFields(){if(workflow==null)return;for(FieldRef f:fields)try{JSONObject n=workflow.optJSONObject(f.node);if(n!=null)n.getJSONObject("inputs").put(f.key,coerce(f.edit.getText().toString()));}catch(Exception ignored){}}
    private Object coerce(String raw){String s=raw==null?"":raw.trim();if("true".equalsIgnoreCase(s))return true;if("false".equalsIgnoreCase(s))return false;try{if(s.matches("-?\\d+"))return Long.parseLong(s);if(s.matches("-?\\d+\\.\\d+"))return Double.parseDouble(s);}catch(Exception ignored){}return raw==null?"":raw;}
    private void saveWorkflow(){prefs().edit().putString(KEY_WORKFLOW,workflow==null?"{}":workflow.toString()).putString(KEY_OPTIONS,options==null?"{}":options.toString()).apply();}
    private boolean validTemplate(TemplateItem t){return t!=null&&!safe(t.name).trim().isEmpty()&&!safe(t.source).trim().isEmpty();}
    private String templateHay(TemplateItem t){return displayTitle(t)+" "+safe(t.name)+" "+safe(t.description)+" "+safe(t.category)+" "+safe(t.source);}
    private String displayTitle(TemplateItem t){return nonEmpty(t.title,t.name);}

    private View statusChip(){String b=activeBase();LinearLayout c=row();c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(12),0,dp(12),0);c.setBackground(bg(surface(),12,stroke(),1));c.addView(text(b.isEmpty()?"○":"●",16,b.isEmpty()?mutedColor():rgb(66,184,93)),new LinearLayout.LayoutParams(dp(24),dp(38)));TextView l=muted(b.isEmpty()?"Tap to set ComfyUI URL":hostLabel(b),12);l.setSingleLine(true);c.addView(l,new LinearLayout.LayoutParams(0,dp(38),1));TextView ar=muted("›",20);ar.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);c.addView(ar,new LinearLayout.LayoutParams(dp(24),dp(38)));c.setOnClickListener(v->topPanel.setVisibility(topPanel.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE));return c;}
    private View header(String h,String sub){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.addView(title(h,28));TextView s=muted(sub,14);s.setMaxLines(2);b.addView(s);return b;}
    private View cardTitle(String icon,String text){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.addView(badge(icon),new LinearLayout.LayoutParams(dp(34),dp(34)));TextView t=title(text,19);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(dp(10),0,0,0);r.addView(t,p);return r;}
    private TextView badge(String s){TextView v=text(s,14,accent());v.setGravity(Gravity.CENTER);v.setBackground(bg(Color.rgb(37,31,22),12,stroke(),1));return v;}
    private TextView chip(String s){TextView v=muted(s,12);v.setGravity(Gravity.CENTER);v.setSingleLine(true);v.setBackground(bg(surface2(),14,stroke(),1));return v;}
    private LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);return r;}
    private LinearLayout card(boolean ac){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(12),dp(12),dp(12));c.setBackground(bg(surface(),16,ac?accent():stroke(),1));return c;}
    private EditText input(String hint,boolean single){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(single);e.setTextColor(Color.WHITE);e.setHintTextColor(mutedColor());e.setTextSize(14);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(surface2(),12,stroke(),1));return e;}
    private Button button(String s,boolean primary,Runnable r){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setSingleLine(true);b.setTextSize(13);b.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));b.setTextColor(primary?accent():Color.WHITE);b.setPadding(dp(6),0,dp(6),0);b.setBackground(bg(primary?Color.rgb(44,35,25):surface2(),12,primary?accent():stroke(),1));b.setOnClickListener(v->r.run());return b;}
    private View nav(String icon,String label,String target){boolean sel=target.equals(screen);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(4),0,dp(4));b.setBackground(sel?bg(Color.rgb(37,31,22),12,accent(),1):bg(Color.TRANSPARENT,12,Color.TRANSPARENT,0));TextView i=text(icon,19,sel?accent():mutedColor());i.setGravity(Gravity.CENTER);b.addView(i,new LinearLayout.LayoutParams(-1,dp(24)));TextView l=text(label,10,sel?accent():mutedColor());l.setGravity(Gravity.CENTER);l.setSingleLine(true);b.addView(l,new LinearLayout.LayoutParams(-1,dp(20)));b.setOnClickListener(v->{screen=target;render();});return b;}
    private void renderNav(){bottomNav.removeAllViews();bottomNav.addView(nav("⊞","Create","create"),weight(58));bottomNav.addView(nav("⌘","Nodes","nodes"),weight(58));bottomNav.addView(nav("▦","Templates","templates"),weight(58));bottomNav.addView(nav("▷","Run","run"),weight(58));bottomNav.addView(nav("▧","Output","output"),weight(58));}
    private LinearLayout.LayoutParams section(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));return p;}
    private LinearLayout.LayoutParams weight(int h){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(h),1);p.setMargins(dp(4),0,dp(4),0);return p;}
    private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h<0?h:dp(h));p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    private TextView title(String s,int sp){TextView t=text(s,sp,Color.WHITE);t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));t.setMaxLines(3);t.setEllipsize(TextUtils.TruncateAt.END);return t;}
    private TextView label(String s){TextView t=text(s,13,Color.rgb(210,210,216));t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));return t;}
    private TextView muted(String s,int sp){return text(s,sp,mutedColor());}
    private TextView text(String s,int sp,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setIncludeFontPadding(false);t.setPadding(dp(2),0,dp(2),dp(5));return t;}
    private GradientDrawable bg(int color,int rad,int st,int sw){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(rad));d.setStroke(dp(sw),st);return d;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private int rgb(int r,int g,int b){return Color.rgb(r,g,b);} private int bgRoot(){return Color.rgb(18,18,19);} private int surface(){return Color.rgb(28,28,30);} private int surface2(){return Color.rgb(33,33,36);} private int stroke(){return Color.rgb(48,48,52);} private int mutedColor(){return Color.rgb(170,170,178);} private int accent(){return Color.rgb(218,143,60);} 
    private void setStatus(String s){if(status==null){status=new TextView(this);status.setVisibility(View.GONE);}status.setText(s);if(templateInfo!=null)templateInfo.setText(s);Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private void openUrl(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){setStatus("Could not open URL.");}}
    private void applyBars(){Window w=getWindow();w.setStatusBarColor(bgRoot());w.setNavigationBarColor(bgRoot());w.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE);} private SharedPreferences prefs(){return getSharedPreferences(PREFS,Context.MODE_PRIVATE);} private String enc(String s){try{return URLEncoder.encode(s==null?"":s,"UTF-8");}catch(Exception e){return"";}} private String encPath(String s){return enc(s).replace("%2F","/");}
    private String readUri(Uri u)throws Exception{InputStream in=getContentResolver().openInputStream(u);if(in==null)throw new Exception("empty file");try{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);return out.toString("UTF-8");}finally{in.close();}}
    private String readText(File f){try{byte[] b=readBytes(f);return b.length==0?"":new String(b,"UTF-8");}catch(Exception e){return"";}} private byte[] readBytes(File f){if(f==null||!f.exists())return new byte[0];ByteArrayOutputStream out=new ByteArrayOutputStream();try{FileInputStream in=new FileInputStream(f);byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);in.close();}catch(Exception ignored){}return out.toByteArray();} private void writeText(File f,String s){try{File p=f.getParentFile();if(p!=null&&!p.exists())p.mkdirs();FileOutputStream out=new FileOutputStream(f);out.write(safe(s).getBytes("UTF-8"));out.close();}catch(Exception ignored){}}
    private String sha1(String s){try{MessageDigest md=MessageDigest.getInstance("SHA-1");byte[] d=md.digest(safe(s).getBytes("UTF-8"));StringBuilder sb=new StringBuilder();for(byte b:d)sb.append(String.format(Locale.US,"%02x",b&0xff));return sb.toString();}catch(Exception e){return String.valueOf(safe(s).hashCode()).replace("-","n");}}
    private String safe(String s){return s==null?"":s;} private String nonEmpty(String v,String f){return v==null||v.trim().isEmpty()?safe(f):v.trim();} private String shortText(String s,int max){if(s==null)return"";return s.length()<=max?s:s.substring(0,Math.max(0,max-1))+"…";} private String shortErr(Exception e){String s=e==null?"":e.getMessage();if(s==null||s.trim().isEmpty())s=e==null?"unknown error":e.getClass().getSimpleName();return s.length()>200?s.substring(0,200)+"…":s;} private String timeAgo(long ts){long sec=Math.max(0,(System.currentTimeMillis()-ts)/1000);if(sec<60)return"just now";long min=sec/60;if(min<60)return min+"m ago";long h=min/60;if(h<24)return h+"h ago";return(h/24)+"d ago";} private String hostLabel(String b){try{return new URL(b).getHost();}catch(Exception e){return b;}} private String prettify(String s){return safe(s).replace('_',' ').replaceAll("([a-z])([A-Z])","$1 $2").trim();}
}
